name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t docker.io/mrlolf/HoneygainAutoClaim:latest .
      - name: Push Docker image to registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push Docker image
        run: docker push docker.io/mrlolf/HoneygainAutoClaim:latest
